package uts; 
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement; 
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JTable;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Aqshal-kun
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        settgl();
        setjm();
    }
    
    String nol_detik = "";
    String nol_menit = "";
    String nol_jam = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ya = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        kasir = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jm = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        print = new javax.swing.JButton();
        save = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(null);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NamaBarang", "HargaBarang", "QTY", "Diskon", "Total", "Kasir", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 830, 270);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(350, 200, 850, 290);

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ID");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 60, 130, 40);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NamaBarang");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(20, 120, 130, 30);

        ya.setForeground(new java.awt.Color(255, 255, 255));
        ya.setText("qty");
        jPanel3.add(ya);
        ya.setBounds(20, 240, 130, 30);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("HargaBarang");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(20, 180, 130, 30);

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        jPanel3.add(harga);
        harga.setBounds(20, 210, 260, 30);
        jPanel3.add(id);
        id.setBounds(20, 90, 260, 30);
        jPanel3.add(nama);
        nama.setBounds(20, 150, 260, 30);

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        jPanel3.add(jumlah);
        jumlah.setBounds(20, 270, 260, 30);
        jPanel3.add(kasir);
        kasir.setBounds(20, 330, 260, 30);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Kasir");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(20, 300, 130, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Form Isian");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(20, 10, 240, 50);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);
        jPanel3.add(jSeparator1);
        jSeparator1.setBounds(0, 60, 310, 340);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(20, 90, 310, 400);

        jPanel4.setBackground(new java.awt.Color(0, 51, 204));
        jPanel4.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("TOKO BUKU BAROKAH");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(50, 10, 480, 50);

        jm.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jm.setForeground(new java.awt.Color(255, 255, 255));
        jm.setText("Jam");
        jPanel4.add(jm);
        jm.setBounds(1020, 30, 170, 40);

        tgl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tgl.setForeground(new java.awt.Color(255, 255, 255));
        tgl.setText("Tanggal");
        jPanel4.add(tgl);
        tgl.setBounds(1020, 0, 170, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 1210, 80);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(null);

        print.setBackground(new java.awt.Color(0, 204, 204));
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel1.add(print);
        print.setBounds(710, 30, 80, 30);

        save.setBackground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save);
        save.setBounds(140, 30, 80, 30);

        delete.setBackground(new java.awt.Color(255, 255, 255));
        delete.setText("DELETE");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete);
        delete.setBounds(230, 30, 80, 30);

        clear.setBackground(new java.awt.Color(255, 255, 255));
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear);
        clear.setBounds(320, 30, 80, 30);

        refresh.setBackground(new java.awt.Color(255, 255, 255));
        refresh.setText("REFRESH");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel1.add(refresh);
        refresh.setBounds(420, 30, 90, 30);

        jPanel5.add(jPanel1);
        jPanel1.setBounds(350, 90, 850, 90);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 0, 1210, 510);

        setBounds(0, 0, 1227, 554);
    }// </editor-fold>//GEN-END:initComponents
 
    public void settgl(){
        java.util.Date skrg = new java.util.Date();
        java.text.SimpleDateFormat kal = new 
            java.text.SimpleDateFormat("dd/MM/yyyy");
        tgl.setText(kal.format(skrg));
    }
    
    public void setjm() {
ActionListener taskPerformer = new ActionListener(){
            public void actionPerformed(ActionEvent evt){
                Date dt = new Date();
                int nilai_jam = dt.getHours();
                int nilai_menit = dt.getMinutes();
                int nilai_detik = dt.getSeconds();
                if(nilai_jam <= 9){
                    nol_jam = "0";
                }
                if(nilai_menit <= 9){
                    nol_menit = "0";
                }
                if(nilai_detik <= 9){
                    nol_detik = "0";
                }
                
                String jam = nol_jam + Integer.toString(nilai_jam);
                String menit = nol_menit + Integer.toString(nilai_menit);
                String detik = nol_detik + Integer.toString(nilai_detik);
                jm.setText("Jam "+jam+":"+menit+":"+detik);
            }
        };
        new Timer(100, taskPerformer).start();
    }
    
    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
 
        int baris = tabel.getSelectedRow();
        if (baris != -1) {
            id.setText(tabel.getValueAt(baris, 0).toString());
            nama.setText(tabel.getValueAt(baris, 1).toString());
            harga.setText(tabel.getValueAt(baris, 2).toString());
            jumlah.setText(tabel.getValueAt(baris, 3).toString());
            kasir.setText(tabel.getValueAt(baris, 6).toString());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_refreshActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
        Date dateFormat = null;

        nama.setText("");
        id.setText("");
        jumlah.setText("");
        harga.setText("");
        kasir.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        int baris = tabel.getSelectedRow();

        if( baris >= 0 ){
            String ID = tabel.getValueAt(baris,0).toString();
            String SQL = "DELETE FROM tb_transaksi WHERE id_barang='"+ID+"'";
            int Status = KoneksiDB.execute(SQL);
            if (Status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }

        }
        else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Dulu","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        if("".equals(id.getText()) || "".equals(nama.getText())  || "".equals(harga.getText())  || "".equals(jumlah.getText())
            || "".equals(kasir.getText()) ){
            JOptionPane.showMessageDialog(this,"Harap Lengkapi Data","Error",JOptionPane.WARNING_MESSAGE);
        }
        else {

            int jumlahnya = Integer.parseInt(String.valueOf(jumlah.getText()));
            int hrg = Integer.parseInt(String.valueOf(harga.getText()));

            int diskon = 10;

            int sub_total = hrg * jumlahnya;

            int total_harga;

            if (sub_total > 100000){
                total_harga = (sub_total)-(sub_total)*diskon/100;
            }
            else
            {
                total_harga= sub_total;
                diskon = 0;
            }

            java.util.Date skrg = new java.util.Date();
            java.text.SimpleDateFormat kal = new
            java.text.SimpleDateFormat("dd/MM/yyyy");
            String date = kal.format(skrg);

            String SQL = "INSERT INTO tb_transaksi(id_barang,nama_barang,harga_barang,qty,diskon,total,kasir,tanggal) "+
            "VALUES('"+id.getText()+"','"+nama.getText()+"','"+harga.getText()+"','"+jumlahnya+"','"+diskon+"','"+total_harga+"','"+kasir.getText()+"','"+date+"')";
            int Status = KoneksiDB.execute(SQL);
            if (Status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Sukses",JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_saveActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat ("Biodata Siswa SMK Telkom Magetan");
        MessageFormat footer = new MessageFormat ("Page {0,number,integer}   ");
        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        }
        catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jm;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kasir;
    private javax.swing.JTextField nama;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel;
    private javax.swing.JLabel tgl;
    private javax.swing.JLabel ya;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
       String kolom[] = {"id_barang","nama_barang","harga_barang","qty","diskon","total","kasir","tanggal"};
       DefaultTableModel dtm = new DefaultTableModel(null,kolom);
       String SQL = "SELECT * FROM `tb_transaksi`";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try {
           while(rs.next()){
               String id_barang = rs.getString(2);
               String nama_barang = rs.getString(3);
               String harga_barang = rs.getString(4);
               String qty = rs.getString(5);
               String diskon = rs.getString(6);
               String total = rs.getString(7);
               String kasir = rs.getString(8);
               String tanggal = rs.getString(9);
               String data[] = {id_barang,nama_barang,harga_barang,qty,diskon,total,kasir,tanggal};
               dtm.addRow(data);
               
           }
       }
       catch (SQLException ex){
           Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE,null,ex);
       }
       tabel.setModel(dtm);
    }  
   
}
